### ISSUE TITLE
ModuleNotFoundError: No module named 'spice' despite installing spiceai

### ISSUE THREAD

**Issue by Daijunfan** [AbanteAI/archive-old-cli-mentat#589]
Hi, I'm trying to run the Mentat project but encountering an issue with the `spice` module.

## Current Behavior
When trying to run `python -m mentat`, I get the following error:
python
Traceback (most recent call last):
File "<frozen runpy>", line 189, in run_module_as_main
File "<frozen runpy>", line 148, in get_module_details
File "<frozen runpy>", line 112, in get_module_details
File "D:\cursor_test\AI_En\mentat-main\mentat\init.py", line 1, in <module>
from mentat.python_client.client import ( # isort: skip
File "D:\cursor_test\AI_En\mentat-main\mentat\python_client\client.py", line 7, in <module>
from mentat.config import Config
File "D:\cursor_test\AI_En\mentat-main\mentat\config.py", line 11, in <module>
from spice.models import TextModel, models
ModuleNotFoundError: No module named 'spice'

## Steps to Reproduce
1. Clone the repository
2. Install dependencies with `pip install -r requirements.txt`
3. Run `python -m mentat`

## Environment
- OS: Windows 10
- Python: 3.10+
- Package versions:
  - spiceai~=0.2.0 (installed from requirements.txt)

## Questions
1. Is `spice` supposed to be a separate module from `spiceai`? The error suggests it's looking for a module named `spice`, but the requirements only list `spiceai`.
2. If they are different, where can I find the `spice` module?
3. If they are the same, is there a naming mismatch in the imports that needs to be fixed?

Any guidance would be appreciated. Thank you!

**Comment by biobootloader** [comment]
`spice` and `spiceai` are the same - `spiceai` is the name when installing from PYPI, `spice` is the name when using it in python code.

I'm not sure why you are getting this error, but we haven't been updating the mentat / spice projects for several months so there are probably a lot of issues with them. We've been focused on our mentat github bot: mentat.ai
